version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: agromarket_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: agromarket
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data:
